#!/usr/bin/env node
"use strict";

const ADAPTER_TYPES = Object.freeze({
  HTML_ENTRY_URL: "HTML_ENTRY_URL",
  HTML_SEARCH_THEN_ENTRY: "HTML_SEARCH_THEN_ENTRY",
  OFFICIAL_JSON_API: "OFFICIAL_JSON_API",
  OFFICIAL_SEARCH_API: "OFFICIAL_SEARCH_API",
  SERVER_RENDERED_DICTIONARY: "SERVER_RENDERED_DICTIONARY",
  JS_RENDERED_SEARCH: "JS_RENDERED_SEARCH",
  RULE_DOCUMENT: "RULE_DOCUMENT",
  PDF_OR_OFFICIAL_NORM_DOCUMENT: "PDF_OR_OFFICIAL_NORM_DOCUMENT",
  BLOCKED_OFFICIAL_SOURCE: "BLOCKED_OFFICIAL_SOURCE",
});

module.exports = { ADAPTER_TYPES };
